### PR TITLE
Pr/7

### PR DESCRIPTION
**Pull request by shawneetap**
@rgupta-okta after I deleted pr/4 I lost the progress with my gruntfile.js. I didnt realize that if you delete a branch, it will alter your files locally. That's okay though, I needed brushing up after the long holiday :)

### CODE REVIEW

**Comment by rgupta-okta** [comment]
Unless you deleted the branch remotely, you can probably get it back from github. I think learning how to use git properly is very useful. 

https://help.github.com/articles/good-resources-for-learning-git-and-github/ is a good site with a lot of links. You don't need to know everything about git/github (I definitely don't), but if you're in a certain situation, knowing what to search for is very useful. Also, the beauty of git is that you can almost always get out of nasty situation.

With this specific Pull Request, you have two commits, one which is in the #8. For this PR, try doing a interactive rebase on master and getting rid of the added gitignore commit or squashing the commits into one.

**Comment by shawneetap** [comment]
Gah! I made it worse. I got the rebase thing working, but then when I got to push, it throws an error saying "! [rejected]  pr/7 -> pr/7 (non-fast-forward)". I finally got it by just using the "git push --force" command.

**Comment by rgupta-okta** [comment]
That's actually expected! When you change the history like that you have to do a force push. This is what devs do. They create a topic branch, work on it, and force push to their **remote topic branch**. As long as you're not force pushing to your remote master branch, you're generally ok.

**Comment by rgupta-okta** [comment]
looks good! :haircut:

**Comment by shawneetap** [comment]
So when it all looks good, do I go ahead and merge the pull request?

**Comment by rgupta-okta** [comment]
yup!

**Pull request merged**
